library(dplyr)
library(readr)
joblist <- list.files("data", "joblist.+csv", full.names = TRUE)
joblist <- purrr::map_df(joblist, read_csv, col_types = cols(id = col_character()))
joblist <- joblist[,-4] %>% distinct()
if(!dir.exists("data/joblist")) dir.create("data/joblist")
readr::write_csv(joblist, file = "data/joblist/joblist_collection.csv")
